--- #YAML:1.0
name:               CWB-CQP-More
version:            0.03
abstract:           A higher level interface for CWB::CQP
author:
    - Alberto Simoes <ambs@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    CWB:           3
    Encode:        0
    POSIX::Open3:  0.01
    Test::More:    0
    Try::Tiny:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
